### ISSUE TITLE
Allow Instrumentation of managed assemblies loaded by .Net Core Profilers

### ISSUE THREAD

**Issue by wyattm124** [coverlet-coverage/coverlet#1194]
Hello,

Our team needs are unique in that we would like to get the code coverage results using the `coverlet.console.exe` of a managed assembly that is loaded by our custom .Net Core profiler. Unfortunately, if we start the coverlet global tool with `CORECLR_ENABLE_PROFILING=1` to allow profiling of the target test application, the assembly that we wish to instrument is loaded by the profiler before the `coverlet.console.exe` used by the coverlet global tool is executed. Therefore, the desired assembly cannot be instrumented because it is already in use by another process. You can see the error here : 

```
Unable to instrument module: C:\***\bin\Debug\netcoreapp3.1\***.netstandard.dll because : The process cannot access the file 'C:\***\bin\Debug\netcoreapp3.1\***.netstandard.dll' because it is being used by another process.
One or more errors occurred. (The process cannot access the file 'C:\***\bin\Debug\netcoreapp3.1\***.netstandard.dll' because it is being used by another process.)

...


at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Coverlet.Core.Helpers.FileSystem.Copy(String sourceFileName, String destFileName, Boolean overwrite) in C:\***\coverlet\src\coverlet.core\Helpers\FileSystem.cs:line 32
   at Coverlet.Core.Helpers.InstrumentationHelper.<>c__DisplayClass14_1.<RestoreOriginalModules>b__0() in C:\***\coverlet\src\coverlet.core\Helpers\InstrumentationHelper.cs:line 258
   at Coverlet.Core.Helpers.RetryHelper.<>c__DisplayClass0_0.<Retry>b__0() in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 25
   at Coverlet.Core.Helpers.RetryHelper.Do[T](Func`1 action, Func`1 backoffStrategy, Int32 maxAttemptCount) in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 52
   --- End of inner exception stack trace ---
   at Coverlet.Core.Helpers.RetryHelper.Do[T](Func`1 action, Func`1 backoffStrategy, Int32 maxAttemptCount) in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 59
   at Coverlet.Core.Helpers.RetryHelper.Retry(Action action, Func`1 backoffStrategy, Int32 maxAttemptCount) in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 23
   at Coverlet.Core.Helpers.InstrumentationHelper.RestoreOriginalModules() in C:\***\coverlet\src\coverlet.core\Helpers\InstrumentationHelper.cs:line 256
   at Coverlet.Core.Helpers.InstrumentationHelper.<.ctor>b__6_0(Object s, EventArgs e) in C:\***\coverlet\src\coverlet.core\Helpers\InstrumentationHelper.cs:line 27
   at System.AppContext.OnProcessExit()
 ---> (Inner Exception #1) System.IO.IOException: The process cannot access the file 'C:\***\bin\Debug\netcoreapp3.1\***.netstandard.dll' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Coverlet.Core.Helpers.FileSystem.Copy(String sourceFileName, String destFileName, Boolean overwrite) in C:\***\coverlet\src\coverlet.core\Helpers\FileSystem.cs:line 32
   at Coverlet.Core.Helpers.InstrumentationHelper.<>c__DisplayClass14_1.<RestoreOriginalModules>b__0() in C:\***\coverlet\src\coverlet.core\Helpers\InstrumentationHelper.cs:line 258
   at Coverlet.Core.Helpers.RetryHelper.<>c__DisplayClass0_0.<Retry>b__0() in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 25
   at Coverlet.Core.Helpers.RetryHelper.Do[T](Func`1 action, Func`1 backoffStrategy, Int32 maxAttemptCount) in C:\***\coverlet\src\coverlet.core\Helpers\RetryHelper.cs:line 52<--

...
```

Where `***.netstandard.dll` is the managed assembly loaded by the profiler. Sorry for the `***`'s, it is to redact sensitive information.

We were able to avoid this problem and get good coverage results of the assembly by setting  `CORECLR_ENABLE_PROFILING=0` before using the coverlet global tool, then setting `CORECLR_ENABLE_PROFILING=1` right before the call to `process.Start()` within the `Program.cs` file of the `coverlet.console` project.

Is there a similar solution to allow this functionality with the coverlet global tool as it is? Or would we be able to submit a PR to add this functionality more programmatically?

**Comment by MarcoRossignoli** [comment]
It should work if you create a "proxy" process that set CORECLR_ENABLE_PROFILING and start profiler, I mean coverlet instrument dll and after "start something" and wait for exit, if that "something" is a "profiler starter" you should been able to set env var or am I missing something?

**Comment by wyattm124** [comment]
For any process which is started with CORECLR_ENABLE_PROFILING=1, the CLR in that process will immediately try to load the appropriate profiler and its dependencies. I am not sure how a proxy process would fix this issue, maybe a small illustration will clarify the problem I mentioned. Take the following PowerShell commands, where `A.dll` is a dependency for the profiler, and `B.exe` is the test app that we want to profile. The goal is to see the code coverage for `A.dll` as `B.exe` is executed :

```
$env:CORECLR_ENABLE_PROFILING=1
...
coverlet.console.exe "<path to A.dll>\" --target "<path to B.exe>\B.exe"
```

Note that `coverlet.console.exe` is executed in a child process of the process that executes the PowerShell commands. Call the first process `X`  and the process that runs `coverlet.console.exe` process `Y`. Also, coverlet executes the test app in a child process of `Y`, call this new process `Z`. In this way the process tree is : `X->Y->Z`

The issue is I can only set profiling in `X`, but then `A.dll` is in use when `Y` starts because as soon as a profiler is loaded for `Y`, so to are all of its dependencies, thus `Y` cannot instrument `A.dll` and throws an error.

We would like an option to set CORECLR_ENABLE_PROFILING=1 within `Y` so that `Y` is not profiled, but `Z` is. In this way `Y` can instrument `A.dll`, then as `B.exe` is run it is profiled with an instrumented `A.dll`, there are no errors, and we get the code coverage of `A.dll` as desired.

Since raising this issue, I learned that our profiler does have advanced configuration parameters available to delay being loaded until `B.exe` is executed so we can get the desired behavior. However, in general this is not possible, so I thought I should still give this description of the problem.

**Comment by MarcoRossignoli** [comment]
Sorry for late answer, but my idea is pretty simple, coverlet instruments A and start B so if we add a C layer that start B with that env set or run a powershell script that set that env and start B?

```
coverlet.console.exe "<path to A.dll>\" --target " ProxyPricessWithEnvSet.ex --processPath <path to B.exe>\B.exe"
```
Something like that?

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
