### ISSUE TITLE
Coverlet is unable to instrument any modules for my test project

### ISSUE THREAD

**Issue by KBDVisma** [coverlet-coverage/coverlet#1330]
Hi all,

What could cause this to happen?:

**Symbols were found but are not matching the assembly**

After updating to the most recent version (3.1.2) I get this stacktrace (3.1.0 only threw the exception message):

```
Unable to instrument module:
Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Coverlet.Core.Instrumentation.Instrumenter.CreateReachabilityHelper() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 196
   at Coverlet.Core.Instrumentation.Instrumenter.InstrumentModule() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 205
   at Coverlet.Core.Instrumentation.Instrumenter.Instrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 145
   at Coverlet.Core.Coverage.PrepareModules() in /_/src/coverlet.core/Coverage.cs:line 135 
```
I'm on a solution with a custom build set up, all dlls (and related) are copied to a single bin folder (deterministic build). I suspect this complicates adding coverage because if I isolate my test and business code to a separate solution then coverlet is able to pull coverage from that just fine.

Any pointers to what the cause could be?

**Comment by MarcoRossignoli** [comment]
Maybe the "single" folder contains pdb of different build(for same dll), pdb is specific to every build so different build of same dll will have different pdb and match could fail.
Can you provide a simple repro of the issue?
