### ISSUE TITLE
datacollector.exe Unable to instrument module: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.2.0'

### ISSUE THREAD

**Issue by thoma01** [coverlet-coverage/coverlet#1332]
Test project created with xUnit v2.4.1 and Microsoft.NET.Test.Sdk v17.1.0 and coverlet.collector v3.1.2

Error from log.datacollector.txt
```
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101538449, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101539974, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'REST.Test\publish'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101544437, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101545465, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'publish\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101545985, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101546955, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101547941, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101548431, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\V1'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101549452, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\V1\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101550684, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\V1\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101551193, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101556124, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.797, 23045101557219, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101557775, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PrivateAssemblies'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101562500, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101563591, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PrivateAssemblies\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101564101, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PublicAssemblies'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101564998, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PublicAssemblies\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101565946, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PublicAssemblies\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101566440, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.798, 23045101567333, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101568309, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101568827, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101569940, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101571232, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101571778, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE'.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101572713, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\System.Reflection.Metadata.dll', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101573735, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\System.Reflection.Metadata.exe', returning.
TpTrace Information: 0 : 17336, 1, 2022/05/09, 14:42:45.799, 23045101574786, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Failed to load assembly.
TpTrace Warning: 0 : 17336, 1, 2022/05/09, 14:42:45.818, 23045101763017, datacollector.exe, [coverlet]Unable to instrument module: 'publish\REST.dll'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Coverlet.Core.Helpers.InstrumentationHelper.HasPdb(String module, Boolean& embedded)
   at Coverlet.Core.Instrumentation.Instrumenter.CanInstrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 92
   ```
   
   It seems in Microsoft.NET.Test.Sdk v17.1.0 they use System.Reflection.Metadata v1.6.0 which is conflicting.
   
   coverlet.runsettings file
   ```
   <?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <Format>cobertura</Format>
          <Include>[REST*]*</Include>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Query to run tests with code coverage 
```
vstest.console.exe REST.Test\publish\REST.Test.dll /Collect:"XPlat Code Coverage" /settings:coverlet.runsettings /diag:TestResults\log.txt
```

This error is blocking me from making any progress with coverlet. Any help would be greatly appreciated.

**Comment by thoma01** [comment]
@MarcoRossignoli Is there anyone that can look into this? Fully blocking the use of coverlet in newer projects.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting it I'll take a look asap.

**Comment by thoma01** [comment]
@MarcoRossignoli Any update?

**Comment by MarcoRossignoli** [comment]
@thoma01 have you tried to bump to 17.2.0?

**Comment by thoma01** [comment]
@MarcoRossignoli Same error in Microsoft.NET.Test.Sdk v17.2.0

**Comment by thoma01** [comment]
@MarcoRossignoli The problem is that `Microsoft.NET.Test.Sdk` and `coverlet.collector` have different version requirements for `System.Reflection.Metadata` which will *always* be in conflict. They will need to be in sync; `coverlet.collector` needs to upgrade the version of `System.Reflection.Metadata` to match that of `Microsoft.NET.Test.Sdk`.

**Comment by tonyhallett** [comment]
This also occurs when specifying the coverlet collector in runsettings and running Visual Studio Test Explorer.
With both VS2019 16.11.7 and VS2022 17.1.0

From TestPlatformLogs\...\logs.datacollector....text for VS2022 ( relevant parts )

```
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.511, 6577976728932, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.511, 6577976730386, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Users\tonyh\.nuget\packages\coverlet.collector\3.1.2\build\netstandard1.0'. 
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.513, 6577976745181, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension.  ****************** finds 1.4.3
								
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.513, 6577976750052, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform'.
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.513, 6577976753828, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension. ****************** finds 1.4.3
								
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.514, 6577976754913, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies'.
TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.514, 6577976760285, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension. ****************** finds 5.0.0

TpTrace Information: 0 : 21180, 1, 2022/06/08, 09:39:31.515, 6577976771506, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Failed to load assembly.
								
TpTrace Warning: 0 : 21180, 1, 2022/06/08, 09:39:31.540, 6577977020051, datacollector.exe, [coverlet]Unable to instrument module: 'C:\Users\tonyh\source\repos\XPlatInRunSettings\NUnitTestProject\bin\Debug\net6.0\Microsoft.TestPlatform.CommunicationUtilities.dll'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Coverlet.Core.Helpers.InstrumentationHelper.HasPdb(String module, Boolean& embedded)
at Coverlet.Core.Instrumentation.Instrumenter.CanInstrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 92
```

And fusion log for VS2019
```
*** Assembly Binder Log Entry  (08/06/2022 @ 11:26:13) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\datacollector.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = datacollector.exe
Calling assembly : coverlet.core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31d7fc2a7e877089.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\datacollector.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\System.Reflection.Metadata.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata/System.Reflection.Metadata.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\tonyh\.nuget\packages\coverlet.collector\3.1.2\build\netstandard1.0\System.Reflection.Metadata.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata/System.Reflection.Metadata.DLL.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata/System.Reflection.Metadata.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (08/06/2022 @ 11:26:13) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\datacollector.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = datacollector.exe
Calling assembly : coverlet.core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31d7fc2a7e877089.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\datacollector.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\System.Reflection.Metadata.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata/System.Reflection.Metadata.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/System.Reflection.Metadata/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\tonyh\.nuget\packages\coverlet.collector\3.1.2\build\netstandard1.0\System.Reflection.Metadata.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata/System.Reflection.Metadata.DLL.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata.EXE.
LOG: Attempting download of new URL file:///C:/Users/tonyh/.nuget/packages/coverlet.collector/3.1.2/build/netstandard1.0/System.Reflection.Metadata/System.Reflection.Metadata.EXE.
LOG: All probing URLs attempted and failed.

```

So coverlet.core has a reference to 1.4.2 and coverlet.collector to 1.4.3.

This was introduced in https://nuget.info/packages/coverlet.collector/3.1.0

https://nuget.info/packages/coverlet.collector/3.0.3 includes System.Reflection.Metadata 1.4.2 - using this version there is no issue with Visual Studio Test Explorer and XPlat code coverage in runsettings.

**Comment by thoma01** [comment]
@MarcoRossignoli I am programming in Visual Studio 2022 and the version of vstest is in the 17.x series... I cannot use any SDK from the 16.x series in that case, it all conflicts.

There needs to a fix, and there should be a compatibility chart in the README.md of this project.

**Comment by tonyhallett** [comment]
@thoma01 
Perhaps you can use version 3.1 and the TestAdapterPath command line option or runsettings TestAdaptersPaths ?

**Comment by thoma01** [comment]
@tonyhallett Not sure what that will help with?

**Comment by tonyhallett** [comment]
Resolve the assembly from the coverlet.collector assembly that has

**Comment by tonyhallett** [comment]
Correction - I should have said version 3.0.3

With a simple  XUnit 2.4.1 test project TestProject1, Microsoft.NET.Test.Sdk 17.1.0 and coverlet 3.1.2

vstest.console.exe TestProject1/bin/debug/net6.0/TestProject1.dll /Collect:"XPlat Code Coverage" /settings:coverlet.runsettings /diag:TestResults\log.txt /TestAdapterPath:"C:\Users\tonyh\.nuget\packages\coverlet.collector\3.1.2\build\netstandard1.0"

	TpTrace Information: 0 : 13680, 1, 2022/06/08, 23:18:17.219, 7069279249182, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
	TpTrace Information: 0 : 13680, 1, 2022/06/08, 23:18:17.220, 7069279250506, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Searching in: 'C:\Users\tonyh\.nuget\packages\coverlet.collector\3.1.2\build\netstandard1.0'.
TpTrace Information: 0 : 13680, 1, 2022/06/08, 23:18:17.222, 7069279272540, datacollector.exe, AssemblyResolver.OnResolve: System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: File exists but version/public key is wrong. Try next extension.

When using 3.0.2 that I have.

vstest.console.exe TestProject1/bin/debug/net6.0/TestProject1.dll /Collect:"XPlat Code Coverage" /settings:coverlet.runsettings /diag:TestResults\log.txt /TestAdapterPath:"C:\Users\tonyh\.nuget\packages\coverlet.collector\3.0.2\build\netstandard1.0"

Coverage results are produced.

Also works with Microsoft.NET.Test.Sdk Version 16.11.0 that the XUnit project template came with.

**Comment by tonyhallett** [comment]
> I appreciate all the efforts to find a workaround, but I need a proper solution that I will be able to use in CI/CD environments.

No problem.  Of course a workaround is not ideal.  I am intrigued though, have you tried the TestAdapterPath with version 3.0.3 ?

**Comment by thoma01** [comment]
@tonyhallett I will give it a try locally, and hopefully that will work. If so, I can use that temporarily in a local environment to get some results. Ultimately this method will not be possible in my CI/CD environments.

**Comment by Bertk** [comment]
System.Reflection.Metadata v1.6.0 is used with PR #1510

**Comment by kolrami** [comment]
@Bertk , thank you for providing a fix for this. I also ran into this issue and wonder how to solve it. Is there already a plan for a new release of coverlet including your PR #1510 and the update of the System.Reflection.Metadata?

**Comment by Bertk** [comment]
related #1536

**Comment by cw397** [comment]
This issue is affecting us too so thanks very much for the fix @Bertk . Like @kolrami, we would really appreciate a new release of coverlet to include the fix. Is there any word on when this might be?

**Comment by Bertk** [comment]
A release of coverlet packages will be done after #1518 is resolved.

**Comment by cw397** [comment]
@Bertk It looks like #1518 is now solved, does this mean that a release is not far away?
