### ISSUE TITLE
Default parameter value of type System.IO.SearchOption excludes assembly from coverage report

### ISSUE THREAD

**Issue by andy250** [coverlet-coverage/coverlet#1380]
Here is the repro solution in .net6 C# and using xunit as test framework: https://github.com/andy250/coverlet-issue-defparam

```
cd CoverletWebApp
dotnet clean
dotnet build
cd ..\CoverletWebAppTest
coverlet bin\Debug\net6.0\CoverletWebAppTest.dll --target "dotnet" --targetargs "test --no-build"
```

The output will contain `CoverletTestTools` in the list of assemblies with coverage calculated. Then go into `CoverletTestTools\FileSystem.cs` and uncomment line 5 and comment line 6 - adding default value for parameter `searchOption`. Run above commands again and there will be a warning:

```
Unable to instrument module: bin\Debug\net6.0\CoverletTestTools.dll
Mono.Cecil.ResolutionException: Failed to resolve System.IO.SearchOption
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Coverlet.Core.Instrumentation.Instrumenter.InstrumentModule() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 335
   at Coverlet.Core.Instrumentation.Instrumenter.Instrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 145
   at Coverlet.Core.Coverage.PrepareModules() in /_/src/coverlet.core/Coverage.cs:line 135
```

And the `CoverletTestTools` will be gone from list of assemblies. Apparently other default arguments (like strings) do not cause such issue.

**Comment by MarcoRossignoli** [comment]
We have some cases with this issue related to cecil assembly resolution https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#failed-to-resolve-assembly-during-instrumentation

Can you enable the diagnostics and check if this is another scenario like that? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#coverlet-global-tool
