### ISSUE TITLE
Getting IOException in Coverlet | Intermittent but Frequent Issue

### ISSUE THREAD

**Issue by PersonalFork** [coverlet-coverage/coverlet#1436]
Version : 
"coverlet.collector" Version="3.2.0"
"coverlet.msbuild" Version="3.2.0"
.NET 6.0.306

Command : `dotnet test /p:ParallelizeTestCollections=false /p:Configuration=Release --collect:\"XPlat Code Coverage\" --settings coverage.runsettings --logger trx --no-build`

**Two Issues :**
1.  A total of 1 test files matched the specified pattern.
Data collector 'XPlat code coverage' message: [coverlet]Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to get coverage result
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\jenkins\AppData\Local\Temp\Org.SupportManager.Client.AgentContracts_334da500-e861-41cd-a413-c86342a7bbf2' because it is being used by another process.

2.  A total of 1 test files matched the specified pattern.
Data collector 'XPlat code coverage' message: [coverlet]Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to get coverage result
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at Coverlet.Core.Coverage.CalculateCoverage() in /_/src/coverlet.core/Coverage.cs:line 414
   at Coverlet.Core.Coverage.GetCoverageResult() in /_/src/coverlet.core/Coverage.cs:line 161
   at Coverlet.Collector.DataCollection.CoverageWrapper.GetCoverageResult(Coverage coverage) in /_/src/coverlet.collector/DataCollection/CoverageWrapper.cs:line 53
   at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageResult() in /_/src/coverlet.collector/DataCollection/CoverageManager.cs:line 92
   --- End of inner exception stack trace ---
   at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageResult() in /_/src/coverlet.collector/DataCollection/CoverageManager.cs:line 97
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionEnd(Object sender, SessionEndEventArgs e) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 161.

**Comment by Bertk** [comment]
Hi,

please use latest version of `coverlet.collector` and try again. Use only one coverlet PackageReference  in test project.

https://github.com/coverlet-coverage/coverlet/blob/master/README.md#vstest-integration-preferred-due-to-known-issue

```
<PackageReference Include="coverlet.collector" Version="6.0.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

The second topic is also mentioned in [known issues](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#upgrade-coverletcollector-to-version--100)

**Comment by viceice** [comment]
seeing this too 😕 

```
Data collector 'XPlat code coverage' message: [coverlet]Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to get coverage result
---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
  at System.IO.BinaryReader.InternalRead(Int32 numBytes)
  at System.IO.BinaryReader.ReadInt32()
  at Coverlet.Core.Coverage.CalculateCoverage() in /_/src/coverlet.core/Coverage.cs:line 414
  at Coverlet.Core.Coverage.GetCoverageResult() in /_/src/coverlet.core/Coverage.cs:line 161
  at Coverlet.Collector.DataCollection.CoverageWrapper.GetCoverageResult(Coverage coverage) in /_/src/coverlet.collector/DataCollection/CoverageWrapper.cs:line 57
  at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageResult() in /_/src/coverlet.collector/DataCollection/CoverageManager.cs:line 95
  --- End of inner exception stack trace ---
  at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageResult() in /_/src/coverlet.collector/DataCollection/CoverageManager.cs:line 100
  at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageReports() in /_/src/coverlet.collector/DataCollection/CoverageManager.cs:line 83
  at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionEnd(Object sender, SessionEndEventArgs e) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 164.
```

Using `coverlet.collector` v6.0.0

**Comment by bruno-garcia** [comment]
We removed coverlet in 2021 because of this issue
* https://github.com/getsentry/sentry-dotnet/issues/726

Enough time had passed we decided to give it a try
* https://github.com/getsentry/sentry-dotnet/pull/3004

Even within the PR adding coverlet we ended up hitting this issue again:
* https://github.com/getsentry/sentry-dotnet/actions/runs/7425866455/job/20208406903?pr=3004#step:14:146

**Comment by cliffchapmanrbx** [comment]
We observed this issue today as well using the latest 6.0.2 release. We're trying the various suggestions to work around it.

**Comment by REscobar** [comment]
I was observing an issue similar to this reported on testfx (https://github.com/microsoft/testfx/issues/2563#issuecomment-2151062114), having random fails with various causes, testing many versions from 1.3.0 to 6.0.2 all failed (1.3.0 had previously worked flawlessly on .net core 3.1 days), a hunch made me think this could be related to race conditions like writing to a dll while it's being read, so changed my command to limit the cpu count during testing by adding `-maxcpucount:1` to the `dotnet test ...` and this seems to have solved the issues (50+ builds and not a single crash), mind you that this only happened to me when running inside a container, when running directly on my dev machine or wsl it worked 100%

**Comment by nhanvolac** [comment]
Please help to fix the issue, I also encountered the same problem...

**Comment by caspChristian** [comment]
We have a solution with several test projects running in parallel, setting `maxcpucount:1` is not an option since that would make the test runs take 4-10 times as long.
A proper solution here would be to have all files being instrumented before any test runs, and there should not be any need to restore the instrumentation after run since this is done in CI the files are thrown away anyways.
