### ISSUE TITLE
Project names ending in '.Collector' causes IOException

### ISSUE THREAD

**Issue by mdenhoedt** [coverlet-coverage/coverlet#1472]
I tried a few project names ending with `.Collector` for the implementation project and `.Collector.Test` for the test project. After running:

```powershell
dotnet test .\X.Usage.Collector.Tests\X.Usage.Collector.Tests.csproj --configuration Release --logger trx --results-directory coverlet --collect "XPlat Code coverage"
```

Causes the testing to fail with the following stacktrace:
```
Data collector 'XPlat code coverage' message: [coverlet]Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to instrument modules
 ---> System.AggregateException: One or more errors occurred. (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.) (The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.)
 ---> System.IO.IOException: The process cannot access the file 'D:\src_git\repo\Backend\X.Usage.Collector.Tests\bin\Release\net6.0\X.Usage.Collector.dll' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Coverlet.Core.Helpers.FileSystem.Copy(String sourceFileName, String destFileName, Boolean overwrite) in /_/src/coverlet.core/Helpers/FileSystem.cs:line 35
   at Coverlet.Core.Helpers.InstrumentationHelper.<>c__DisplayClass13_0.<RestoreOriginalModule>b__0() in /_/src/coverlet.core/Helpers/InstrumentationHelper.cs:line 246
   at Coverlet.Core.Helpers.RetryHelper.<>c__DisplayClass0_0.<Retry>b__0() in /_/src/coverlet.core/Helpers/RetryHelper.cs:line 28
   at Coverlet.Core.Helpers.RetryHelper.Do[T](Func`1 action, Func`1 backoffStrategy, Int32 maxAttemptCount) in /_/src/coverlet.core/Helpers/RetryHelper.cs:line 55
....
```

This problem doesn't happen when I use `--collect "Code Coverage"`, so without the "XPlat" part.

Is there somewhere some logic that prevent ending the name of a C# project with `Collector`?

**Comment by petli** [comment]
Unfortunately there is an issue with vstest with projects ending in `collector.dll` (see #1386 for discussion and link to vstest issue). I don't know why the standard .NET code coverage doesn't run into an issue, but would hazard a guess that one doesn't use the dynamic loading of collector DLLs but uses a built-in collector.

As #1386 suggests you can use the msbuild or command line drivers instead, but they have other issues: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by mdenhoedt** [comment]
Ok, that's unfortunate, I will rename the projects (and assembly names).
