### ISSUE TITLE
[BUG] Coverlet.Collector produces empty report when Mediator.SourceGenerator is referenced

### ISSUE THREAD

**Issue by alex-zyl** [coverlet-coverage/coverlet#1718]
**Describe the bug**
Please share a clear and concise description of the problem.

**To Reproduce**
1. Create WebAPI and UnitTest projects from template.
2. Add Mediator packages to WebAPI project
```xml
<ItemGroup>
  <PackageReference Include="Mediator.Abstractions" Version="3.0.0-preview.27" />
  <PackageReference Include="Mediator.SourceGenerator" Version="3.0.0-preview.27" >
  <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers;</IncludeAssets>
  </PackageReference>
</ItemGroup>
```
3. Run tests
```
dotnet test .\TestProject.sln --configuration Debug --collect:"XPlat Code Coverage" --diag:log.txt
```

**Expected behavior**
Coverage report includes types from analyzed project.

**Actual behavior**
Coverage report is empty.

```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0" branch-rate="0" version="1.9" timestamp="1734109700" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
    * Which coverlet package and version was used?
    `6.0.0`
    * Which version of .NET is the code running on?
    `net8.0`
    * What OS and version, and what distro if applicable?
    `Win11`
    * What is the architecture (x64, x86, ARM, ARM64)?
    `x64`
    * Do you know whether it is specific to that configuration?
    `No`

**Additional context**
log.datacollector contains the following exception
```
TpTrace Information: 0 : 35584, 1, 2024/12/13, 18:07:37.009, 629740483105, datacollector.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.DotNet.PlatformAbstractions, from path: C:\Users\admin\.nuget\packages\coverlet.collector\6.0.0\build\netstandard1.0\Microsoft.DotNet.PlatformAbstractions.dll
TpTrace Verbose: 0 : 35584, 1, 2024/12/13, 18:07:37.012, 629740517319, datacollector.dll, [coverlet]AspNetCoreSharedFrameworkResolver search paths:
TpTrace Verbose: 0 : 35584, 1, 2024/12/13, 18:07:37.012, 629740517703, datacollector.dll, [coverlet]C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All\9.0.0
TpTrace Verbose: 0 : 35584, 1, 2024/12/13, 18:07:37.012, 629740517868, datacollector.dll, [coverlet]C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.0
TpTrace Verbose: 0 : 35584, 1, 2024/12/13, 18:07:37.013, 629740524572, datacollector.dll, [coverlet]Loading D:\Projects\Sandbox\Testcoverage\Testsnet8\bin\Debug\net8.0\testsnet8.deps.json
TpTrace Warning: 0 : 35584, 1, 2024/12/13, 18:07:37.017, 629740570341, datacollector.dll, [coverlet]Unable to instrument module: D:\Projects\Sandbox\Testcoverage\Testsnet8\bin\Debug\net8.0\ProjNet8.dll
Coverlet.Core.Exceptions.CecilAssemblyResolutionException: AssemblyResolutionException for 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   --- End of inner exception stack trace ---
   at Coverlet.Core.Instrumentation.NetstandardAwareAssemblyResolver.TryWithCustomResolverOnDotNetCore(AssemblyNameReference name) in /_/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs:line 215
   at Coverlet.Core.Instrumentation.NetstandardAwareAssemblyResolver.Resolve(AssemblyNameReference name) in /_/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs:line 127
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Coverlet.Core.Instrumentation.Instrumenter.InstrumentModule() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 333
   at Coverlet.Core.Instrumentation.Instrumenter.Instrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 149
   at Coverlet.Core.Coverage.PrepareModules() in /_/src/coverlet.core/Coverage.cs:line 135
```

**Comment by Bertk** [comment]
Thanks a lot for reporting this issue. The current [coverlet.collector](https://github.com/coverlet-coverage/coverlet?tab=readme-ov-file#requirements-coverletcollector) version 6.0.3 targets **netstandard2.0** only. This issue will be solved in the next major version.

**Comment by alex-zyl** [comment]
Thanks for heads up @Bertk 
Can't `NetstandardAwareAssemblyResolver` just be updated to try to lookup an assembly in `refs` folder if not found in main directory?

**Comment by killergege** [comment]
We have a very similar issue

In our solution, we replaced MediatR with Mediator.SourceGenerator.
Since this change, the project that references the Mediator.SourceGenerator is missing from the coverage for the project testing it.
Other side projects are there, but the main one is just missing.
There is no warning or error displayed during build or testing though. I tried to have detailed logs, but found nothing useful.

We found that 2 elements impact the issue:
* Mediator.SourceGenerator
* The .NET version : the issue is there with .NET 10.0.201 but not with .NET 10.0.104

We tried several combinaisons:
* MediatR + 10.0.104 => Coverage output is OK
* MediatR + 10.0.201 => Coverage output is OK
* Mediator + 10.0.104 => Coverage output is OK
* Mediator + 10.0.201 => Coverage output is KO

The suggested solution above to copy the dependency `Microsoft.Extensions.DependencyInjection.Abstractions` manually to the output fixes the issue, but I'm not sure why:

```
    <ItemGroup>
        <Content Include="$(PkgMicrosoft_Extensions_DependencyInjection_Abstractions)\lib\net10.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
```
And updating the reference:
``` 
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" GeneratePathProperty="true" />
```

We are using Coverlet 8.0.1 (but we also have the issue with 6.0.4).

**Comment by Bertk** [comment]
Thank you for sharing this information. When you have a moment, could you please try the **coverlet.collector** preview from the Coverlet nightly build (version [8.1.0-preview-0016-gdcc9d19f60](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly/NuGet/coverlet.collector/overview/8.1.0-preview-0016-gdcc9d19f60)) and let me know how it works for you?

If the issue persists, it would be very helpful if you could share the diagnostic log files so we can take a closer look.

Looking ahead, with .NET 10 it may also be worth considering a migration to the Microsoft Testing Platform along with the `coverlet.MTP` NuGet package.

**Comment by yusyd** [comment]
@Bertk I have the same issue, and I tested the nightly collector `coverlet.collector 8.1.0-preview-0016-gdcc9d19f60`. It still reproduces for me on Windows x64 with .NET SDK `10.0.201`.
I also reproduced the same on Ubuntu in GitHub Actions CI: tests pass, Cobertura is generated, but the assembly is missing from the coverage output.

I created a standalone repro here:
https://github.com/yusyd/coverlet-mediator-repro
With this repro, tests pass and Cobertura is generated, but `Repro.Application` is missing from the coverage output

The datacollector log shows:

```
[coverlet]Unable to instrument module: ...\Repro.Application.dll
Coverlet.Core.Exceptions.CecilAssemblyResolutionException: AssemblyResolutionException for 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

I also tried the workarounds, and none of them fixed it:

- `<PreserveCompilationContext>true</PreserveCompilationContext>`
- `/p:CopyLocalLockFileAssemblies=true`

**Comment by AStarchikov** [comment]
I have the same issue
Was able to reproduce it with @yusyd repo sample

**Comment by Bertk** [comment]
@yusyd could you please try the latest preview of the coverlet.collector package [8.1.0-preview-0018-g64b99d2d05](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly/NuGet/coverlet.collector/overview/8.1.0-preview-0018-g64b99d2d05) when you have a chance? I used the repo sample and this was executed now successfully.

If it resolves the issue on your side, would you mind closing the ticket? That would be greatly appreciated.

**Comment by yusyd** [comment]
@Bertk I tried `coverlet.collector 8.1.0-preview-0018-g64b99d2d05` with the repo sample and another project, and it still reproduces on my side.
Tests pass and Cobertura is generated, but `Repro.Application` is missing from the coverage output

The datacollector log still shows:
```
[coverlet]Unable to instrument module: ...\Repro.Application.dll
Coverlet.Core.Exceptions.CecilAssemblyResolutionException: AssemblyResolutionException for 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```
I noticed that with new changes it now resolves `Microsoft.Extensions.DependencyInjection.Abstractions.dll` first, so something changed, but the instrumentation of `Repro.Application.dll` still fails

Logs from the last run:
[vstest.diag](https://github.com/yusyd/coverlet-mediator-repro/blob/a2377923689c6daff198b116ebb1caf2e956c149/artifacts/vstest.diag.txt)
[vstest.diag.datacollector](https://github.com/yusyd/coverlet-mediator-repro/blob/a2377923689c6daff198b116ebb1caf2e956c149/artifacts/vstest.diag.datacollector.26-04-13_11-35-07_29748_5.txt)

**Comment by Bertk** [comment]
@yusyd I did some small updates and executed the test but could not generated a accurate code coverage file.

```shell
dotnet test .\CoverletMediatorRepro.slnx --no-restore --configuration Release --results-directory .\artifacts\TestResults --collect:"XPlat Code Coverage;Format=cobertura;Exclude=[xunit.*]*,[coverlet.*]*,[Microsoft.Testplatform.*]*;Include=[Repro.*]*" --diag .\artifacts\vstest.diag.txt -p:NuGetAudit=false
```
[Results.zip](https://github.com/user-attachments/files/26680582/Results.zip)

There is another issue #1782 with a Repo for API tests and this creates a valid code coverage file. Maybe some additional settings can be used for this repo as well.

[coverlet-issue-1782.zip](https://github.com/user-attachments/files/26680919/coverlet-issue-1782.zip)

**Comment by yusyd** [comment]
@Bertk I looked into this more and it seems there are two parts to the problem:

1. Something changed in .NET SDK output between `10.0.104` and `10.0.201`
2. coverlet is not handling that changed output well when it tries to instrument a copied project-reference assembly

What I saw in the repro (`coverlet-mediator-repro`):

- With a clean build on SDK `10.0.104`, `Repro.Application` is present in the raw `coverage.cobertura.xml`
- With a clean build on SDK `10.0.201`, `Repro.Application` is missing from the raw coverage file
- On `10.0.201`, coverlet fails while instrumenting with `CecilAssemblyResolutionException` for `Microsoft.Extensions.DependencyInjection.Abstractions`
- In that failing case, the project assembly is copied to the test output, but the needed DI assembly is not
- `RestoreEnablePackagePruning=false` does not fix it

My understanding is:

- The SDK change caused the issue
- The coverlet-specific problem is in `CecilAssemblyResolver`
- When coverlet instruments a copied assembly from test output, it seems to expect that assembly to have its own runtimeconfig or local dependency copy
- If that is missing, coverlet does not check for other `*.runtimeconfig.json` files from the same output folder to find shared-framework assemblies

So my current findings are:

- there does seem to be an SDK/output change between `10.0.104` and `10.0.201`
- but coverlet can probably be made more robust with a small resolver fix in `CecilAssemblyResolver`
- and this does not seem to be the same as `#1782`, because this fails earlier during instrumentation

I opened a PR with a proposed fix for this problem: #1889

**Comment by Bertk** [comment]
Thank you for the PR. Please check and resolve the co-pilot comments. 

Result using the PR solution: [coverage.cobertura.xml](https://github.com/user-attachments/files/26703171/coverage.cobertura.xml)

**Comment by AStarchikov** [comment]
When can we expect a new package with this fix?

**Comment by Bertk** [comment]
The NuGet package has now been released: https://www.nuget.org/packages/coverlet.collector/10.0.0

**Comment by kayarre** [comment]
This appears to be an issue in 10.0.1

**Comment by Bertk** [comment]
> This appears to be an issue in 10.0.1

Please use the latest coverlet.MTP nuget preview package [10.0.2-preview.2.gdfb154275d](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly/NuGet/coverlet.MTP/overview/10.0.2-preview.2.gdfb154275d) 

coverlet.MTP is actively maintained and aligned with the Microsoft Testing Platform (MTP), which is the default test platform starting with .NET 10.

see https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

> [!Important]
>Running MTP projects under VSTest mode is considered legacy in favor of the newer experience in .NET 10 SDK. The support of running under this mode will be removed in MTP version 2 if run with .NET 10 SDK. The support remains available for .NET 9 SDK and earlier for backward compatibility. For more information, see [Migrate to MTP mode of dotnet test](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test#migrate-to-mtp-mode-of-dotnet-test).

>[!Note]
>test example [MediatorApp.Tests](https://github.com/Bertk/coverlet-examples/tree/main/test/MediatorApp.Tests) create test results.
> 

<img width="1034" height="116" alt="Image" src="https://github.com/user-attachments/assets/37520d8b-7c48-4a48-9414-368dfd932fcf" />
